dist: trusty
language: java
jdk:
  - oraclejdk11
before_install:
  - export TZ=Brazil/East
  - chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: "qyUBLwDw1UwXe79r6Lx/p15FSGpt1tFahH9jpvoBnd2ZgF/sSyW/ppz0xCPQI04KQnqGDkh4PXxJobV3EZymIqCDOXSGPBi9JSrc7kzeuDjFeNlU95ddtqyyzvBtxy9IfNef7pdBT/6ZY60YvrN4KWODTPHX0A7vUbOkuCtMJX/8uEdyyGmnUbGF27eWC5VXXkEO4232B6F9lU1Gf/Jbz8boTcwp9GBRZaFzJ6XwufFOwnysBFNKsjWBH3p8IlqjnsIoo1tNxUZZvkiRCycHuAr+kMGJjE+SWl3YSh5T0vPw2rm5Nb74Fn+0xIRt/rz3TeELG/7biAfaNNwTkzxupSBTOW4MG23x7IQsmn8718V09T/iwdn9cZGIGhyALEr39BJgl2nMFg7PHDKY+V59snN7OTM0pvToKN+kjeMwNgliDHYlBXTFKnbu2eO0xGWsT2bC+u67xitnFbk2RgoDCcBpB3o12jd5fuVrWu6HTi7v43p1r7QdEalQ6IjVlKDO1Qe+z0thzU/vAlFOE++JdpIVcP+gdg6XMmSml59UPgPqR/ypWxProqhn7RhnRZU9IyZgFxbl1+1sEmCalx3PD9p1VBdUR/KnMFVE8ZBsZpJm0S/Kw9wlHWhRgwlqVL8CUm4JaIwD9msE5Q9KKrPe0sFePDX7RUHp0Wzyf17Tc/g="
  app: $APP
