dist: trusty
language: java
jdk:
  - oraclejdk11
  before_install:
  - export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    - secure: "de25AUVmRgTnum6h9ag5sR9I82lz7wI4hgqF9WJh+5XNePGFvO7qDYvS8RKHmMWcxGfrMbm6c5MaDXDJ7maGiJxylBMYwbZCmRIsO7314dQ9GxrjfM4mZ0uRNdUs8h5FIIAP2w70gN4QuC9Cfq3egpuwRITiIm8Q4Stt94R2/wQlT/8cEPh3fA3bgqaDre32XNRV2b2oRXqjgl8WRoOsYbkWrsbXdDmlPOhhIUs4yiwp/e7niwih1w4PBL0ZlljiddFaqX4Z+jU/l0eQIILj+p03mQeNMLdA7ZEw8mhTHh+ORsBwWLQg70w4YfWEWU4+eqMnLPVKRaqJzE0kAQXmMmgm4aNm4wSEgXey6ryvWUKz9PBe903jK8CvMgwopDuduXbHInwDcAGx5C1AowX8ggZXzATuHufPyv/3tp7mOOdmaKCE26MHf9pwYh8PgITNOU2wmuCt+oNy//4oxmWnBjmAWGgs8EbTyvEPSb4glxN+PsUYMcGHW0xNtoPzjT4HiC9F1oWCMRD1M9y0HlNeYamuYeDvQ3bT0N3qG3SgJha/2dvRWaTo22cn8aVRON0gcD5MmPMOVDoamL1/TJTQ+CfAufL9VBEgdqM6fOdkEdwxdCtmS6N2eJgNQk2i3hKMJqAOiEg2Hodst11ZwfbkxIeo8xuUd7zMRu619TtlCwQ="
  app: $APP